#Important Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

# Read Data

In [2]:
df = pd.read_csv('HR-Employee-Attrition.csv')

In [3]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [4]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [5]:
# Print column names to verify their existence and exact spelling
print(df.columns)

# Attempt to drop the columns. Adjust the list if the printed output shows different names.
df = df.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours','HourlyRate','MonthlyRate'], axis=1)

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [6]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   object
 10  JobInvolvement            1470 non-null   int64
 11  JobLevel                  1470 non-null   int64
 12  JobRole                   1470 non-null   object
 13  JobSatisfaction           1470 non-null   int64
 14  MaritalStatus             1470 non-null   object
 15  MonthlyIncome             1470 non-null   int64
 16  NumCompaniesWorked        1470 non-null   int64
 17  OverTime                  1470 non-null   object
 18  PercentSalaryHike         1470 non-null   int64
 19  PerformanceRating         1470 non-null   int64
 20  RelationshipSatisfaction  1470 non-null   int64
 21  StockOptionLevel          1470 non-null   int64
 22  TotalWorkingYears         1470 non-null   int64
 23  TrainingTimesLastYear     1470 non-null   int64
 24  WorkLifeBalance           1470 non-null   int64
 25  YearsAtCompany            1470 non-null   int64
 26  YearsInCurrentRole        1470 non-null   int64
 27  YearsSinceLastPromotion   1470 non-null   int64
 28  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(21), object(8)
memory usage: 333.2+ KB

In [8]:
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [9]:
df = pd.get_dummies(df, drop_first=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 43 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   Attrition                          1470 non-null   int64
 2   DailyRate                          1470 non-null   int64
 3   DistanceFromHome                   1470 non-null   int64
 4   Education                          1470 non-null   int64
 5   EnvironmentSatisfaction            1470 non-null   int64
 6   JobInvolvement                     1470 non-null   int64
 7   JobLevel                           1470 non-null   int64
 8   JobSatisfaction                    1470 non-null   int64
 9   MonthlyIncome                      1470 non-null   int64
 10  NumCompaniesWorked                 1470 non-null   int64
 11  PercentSalaryHike                  1470 non-null   int64
 12  PerformanceRating                  1470 non-null   int64
 13  RelationshipSatisfaction           1470 non-null   int64
 14  StockOptionLevel                   1470 non-null   int64
 15  TotalWorkingYears                  1470 non-null   int64
 16  TrainingTimesLastYear              1470 non-null   int64
 17  WorkLifeBalance                    1470 non-null   int64
 18  YearsAtCompany                     1470 non-null   int64
 19  YearsInCurrentRole                 1470 non-null   int64
 20  YearsSinceLastPromotion            1470 non-null   int64
 21  YearsWithCurrManager               1470 non-null   int64
 22  BusinessTravel_Travel_Frequently   1470 non-null   bool
 23  BusinessTravel_Travel_Rarely       1470 non-null   bool
 24  Department_Research & Development  1470 non-null   bool
 25  Department_Sales                   1470 non-null   bool
 26  EducationField_Life Sciences       1470 non-null   bool
 27  EducationField_Marketing           1470 non-null   bool
 28  EducationField_Medical             1470 non-null   bool
 29  EducationField_Other               1470 non-null   bool
 30  EducationField_Technical Degree    1470 non-null   bool
 31  Gender_Male                        1470 non-null   bool
 32  JobRole_Human Resources            1470 non-null   bool
 33  JobRole_Laboratory Technician      1470 non-null   bool
 34  JobRole_Manager                    1470 non-null   bool
 35  JobRole_Manufacturing Director     1470 non-null   bool
 36  JobRole_Research Director          1470 non-null   bool
 37  JobRole_Research Scientist         1470 non-null   bool
 38  JobRole_Sales Executive            1470 non-null   bool
 39  JobRole_Sales Representative       1470 non-null   bool
 40  MaritalStatus_Married              1470 non-null   bool
 41  MaritalStatus_Single               1470 non-null   bool
 42  OverTime_Yes                       1470 non-null   bool
dtypes: bool(21), int64(22)
memory usage: 282.9 KB

In [11]:
df.head(1)

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1,1102,1,2,2,3,2,4,5993,...,False,False,False,False,False,True,False,False,True,True

# Decide Dependant and Independant Elements in Data Set

In [12]:
x=df.drop('Attrition',axis=1)

In [13]:
x

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,2,3,2,4,5993,8,...,False,False,False,False,False,True,False,False,True,True
1,49,279,8,1,3,2,2,2,5130,1,...,False,False,False,False,True,False,False,True,False,False
2,37,1373,2,2,4,2,1,3,2090,6,...,True,False,False,False,False,False,False,False,True,True
3,33,1392,3,4,4,3,1,3,2909,1,...,False,False,False,False,True,False,False,True,False,True
4,27,591,2,1,1,3,1,2,3468,9,...,True,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,3,4,2,4,2571,4,...,True,False,False,False,False,False,False,True,False,False
1466,39,613,6,1,4,2,3,1,9991,4,...,False,False,False,False,False,False,False,True,False,False
1467,27,155,4,3,2,4,2,2,6142,1,...,False,False,True,False,False,False,False,True,False,True
1468,49,1023,2,3,4,2,2,2,5390,2,...,False,False,False,False,False,True,False,True,False,False
1469,34,628,8,3,2,4,2,3,4404,2,...,True,False,False,False,False,False,False,True,False,False

In [14]:
y=df['Attrition']

In [15]:
y

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

#Train Test Split

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test =train_test_split(x,y,test_size=0.3)

In [18]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1029 entries, 5 to 218
Data columns (total 42 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1029 non-null   int64
 1   DailyRate                          1029 non-null   int64
 2   DistanceFromHome                   1029 non-null   int64
 3   Education                          1029 non-null   int64
 4   EnvironmentSatisfaction            1029 non-null   int64
 5   JobInvolvement                     1029 non-null   int64
 6   JobLevel                           1029 non-null   int64
 7   JobSatisfaction                    1029 non-null   int64
 8   MonthlyIncome                      1029 non-null   int64
 9   NumCompaniesWorked                 1029 non-null   int64
 10  PercentSalaryHike                  1029 non-null   int64
 11  PerformanceRating                  1029 non-null   int64
 12  RelationshipSatisfaction           1029 non-null   int64
 13  StockOptionLevel                   1029 non-null   int64
 14  TotalWorkingYears                  1029 non-null   int64
 15  TrainingTimesLastYear              1029 non-null   int64
 16  WorkLifeBalance                    1029 non-null   int64
 17  YearsAtCompany                     1029 non-null   int64
 18  YearsInCurrentRole                 1029 non-null   int64
 19  YearsSinceLastPromotion            1029 non-null   int64
 20  YearsWithCurrManager               1029 non-null   int64
 21  BusinessTravel_Travel_Frequently   1029 non-null   bool
 22  BusinessTravel_Travel_Rarely       1029 non-null   bool
 23  Department_Research & Development  1029 non-null   bool
 24  Department_Sales                   1029 non-null   bool
 25  EducationField_Life Sciences       1029 non-null   bool
 26  EducationField_Marketing           1029 non-null   bool
 27  EducationField_Medical             1029 non-null   bool
 28  EducationField_Other               1029 non-null   bool
 29  EducationField_Technical Degree    1029 non-null   bool
 30  Gender_Male                        1029 non-null   bool
 31  JobRole_Human Resources            1029 non-null   bool
 32  JobRole_Laboratory Technician      1029 non-null   bool
 33  JobRole_Manager                    1029 non-null   bool
 34  JobRole_Manufacturing Director     1029 non-null   bool
 35  JobRole_Research Director          1029 non-null   bool
 36  JobRole_Research Scientist         1029 non-null   bool
 37  JobRole_Sales Executive            1029 non-null   bool
 38  JobRole_Sales Representative       1029 non-null   bool
 39  MaritalStatus_Married              1029 non-null   bool
 40  MaritalStatus_Single               1029 non-null   bool
 41  OverTime_Yes                       1029 non-null   bool
dtypes: bool(21), int64(21)
memory usage: 198.0 KB

In [19]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 441 entries, 878 to 160
Data columns (total 42 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                441 non-null    int64
 1   DailyRate                          441 non-null    int64
 2   DistanceFromHome                   441 non-null    int64
 3   Education                          441 non-null    int64
 4   EnvironmentSatisfaction            441 non-null    int64
 5   JobInvolvement                     441 non-null    int64
 6   JobLevel                           441 non-null    int64
 7   JobSatisfaction                    441 non-null    int64
 8   MonthlyIncome                      441 non-null    int64
 9   NumCompaniesWorked                 441 non-null    int64
 10  PercentSalaryHike                  441 non-null    int64
 11  PerformanceRating                  441 non-null    int64
 12  RelationshipSatisfaction           441 non-null    int64
 13  StockOptionLevel                   441 non-null    int64
 14  TotalWorkingYears                  441 non-null    int64
 15  TrainingTimesLastYear              441 non-null    int64
 16  WorkLifeBalance                    441 non-null    int64
 17  YearsAtCompany                     441 non-null    int64
 18  YearsInCurrentRole                 441 non-null    int64
 19  YearsSinceLastPromotion            441 non-null    int64
 20  YearsWithCurrManager               441 non-null    int64
 21  BusinessTravel_Travel_Frequently   441 non-null    bool
 22  BusinessTravel_Travel_Rarely       441 non-null    bool
 23  Department_Research & Development  441 non-null    bool
 24  Department_Sales                   441 non-null    bool
 25  EducationField_Life Sciences       441 non-null    bool
 26  EducationField_Marketing           441 non-null    bool
 27  EducationField_Medical             441 non-null    bool
 28  EducationField_Other               441 non-null    bool
 29  EducationField_Technical Degree    441 non-null    bool
 30  Gender_Male                        441 non-null    bool
 31  JobRole_Human Resources            441 non-null    bool
 32  JobRole_Laboratory Technician      441 non-null    bool
 33  JobRole_Manager                    441 non-null    bool
 34  JobRole_Manufacturing Director     441 non-null    bool
 35  JobRole_Research Director          441 non-null    bool
 36  JobRole_Research Scientist         441 non-null    bool
 37  JobRole_Sales Executive            441 non-null    bool
 38  JobRole_Sales Representative       441 non-null    bool
 39  MaritalStatus_Married              441 non-null    bool
 40  MaritalStatus_Single               441 non-null    bool
 41  OverTime_Yes                       441 non-null    bool
dtypes: bool(21), int64(21)
memory usage: 84.8 KB

#Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logmodel = LogisticRegression()

In [22]:
logmodel.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [23]:
predictions = logmodel.predict(X_test)

In [24]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.85      0.99      0.91       374
           1       0.20      0.01      0.03        67

    accuracy                           0.84       441
   macro avg       0.52      0.50      0.47       441
weighted avg       0.75      0.84      0.78       441

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
print(confusion_matrix(y_test,predictions))

[[370   4]
 [ 66   1]]